apiVersion: v1
kind: Service
metadata:
  name: my-product-service
spec:
  selector:
    app: my-product-app  # This should match the label in your deployment.yaml
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081   # The port on the container that the app listens to
  type: NodePort          # Exposes the service externally via a static port on each node