apiVersion: v1
kind: Service
metadata:
  name: my-product-service
spec:
  selector:
    app: my-product-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081    # container port
  type: NodePort          # Exposes the service externally via a static port on each node